development:
  data:
    train: ./data/train.json
    test: ./data/test.json
    target: ./data/target.json
    batch_size: 1
    num_workers: 0

  model:
    pretrained_model_dir: ./model
    max_length: 64
    window_size: 2
    d_model: 512
    num_layers: 6
    dropout: 0.1

  log:
    log_dir: ./logs

  train:
    device: "cuda:7"
    epochs: 2
    seed: 200
    lr: 1e-4
    weight_decay: 1e-5
    checkpoint_dir: ./logs/checkpoints-bge
    checkpoint_step: 1
