debug: false

data:
  train: ./data/train.json
  test:
  batch_size: 32
  num_workers: 4

model:
  max_length: 32
  window_size: 2
  d_model: 512
  num_heads: 8
  num_layers: 6
  dim_feedforward: 2048
  dropout: 0.1

log:
  log_dir: ./logs
  model_dir: ./model

train:
  device: cuda
  epochs: 20
  seed: 200
  lr: 5e-5
  weight_decay: 1e-5
