production:
  data:
    train: ./data/train.json
    test: ./data/test.json
    batch_size: 64
    num_workers: 8

  model:
    pretrained_model_dir: ./model
    max_length: 128
    window_size: 2
    d_model: 1024
    num_layers: 6
    dropout: 0.1

  log:
    log_dir: ./logs

  train:
    device: "cuda:7"
    epochs: 50
    seed: 400
    lr: 5e-5
    weight_decay: 1e-5
    checkpoint_dir: ./logs/checkpoints
    checkpoint_step: 25
