development:
  data:
    train: ./data/train.json
    test: ./data/test.json
    batch_size: 1
    num_workers: 0

  model:
    max_length: 32
    window_size: 2
    d_model: 512
    num_heads: 8
    num_layers: 6
    dim_feedforward: 2048
    dropout: 0.1

  log:
    log_dir: ./logs
    model_dir: ./model

  train:
    device: cpu
    epochs: 2
    seed: 200
    lr: 1e-4
    weight_decay: 1e-5
