production:
  data:
    train: ./data/train.json
    test: ./data/test.json
    batch_size: 64
    num_workers: 8

  model:
    pretrained_model_dir: ./model
    max_length: 64
    window_size: 2
    d_model: 1024
    num_layers: 6
    dropout: 0.1

  log:
    log_dir: ./logs

  train:
    device: cuda
    epochs: 50
    seed: 200
    lr: 5e-4
    weight_decay: 1e-5
