debug: true

data:
  train: ./data/train.json
  test:
  batch_size: 32
  num_workers: 4
  tokenizer: ./model/bert-base-chinese

model:
  bert: ./model/bert-base-chinese
  max_length: 32
  window_size: 2
  d_model: 512
  num_heads: 8
  num_layers: 6
  dim_feedforward: 2048
  dropout: 0.1

log:
  dir: ./logs

train:
  lr: 1e-5
  device: cuda
